language: c
compiler:
- clang
script: PLATFORM=TESTING make test_long
install:
- gem install coveralls-lcov
before_install:
- sudo apt-get update -qq
- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq -y libgd2-xpm ia32-libs
  ia32-libs-multiarch; fi
- script/bootstrap.sh
- cd src
after_success:
- PLATFORM=TESTING make coverage
- coveralls-lcov build/tests/coverage.info
deploy:
  provider: releases
  api_key:
    secure: NOSHkTeRCfYcfW6ft8/5xOsEmn0DFrfvJL0UFsDQ9f0dBPoXPMJpgbXr+0i4wbMvwIgAKmJ2SfgvIBcm8IWXhLSMsZiaaTvrbomNgqI8ZIghBdSe6GARaiF/9V/A5l/8zCVMs65Kpo1BssC0BiESpIgoOR/aeF5J6TmCIbUe03k=
  before_deploy: echo "n" | fab release:skip_tests=True
  skip_cleanup: true
  file_glob: true
  file: "./release/openxc-vi-firmware-v*.*.*.zip"
  on:
    repo: openxc/vi-firmware
    tags: true
